// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkCosts.Data;

#nullable disable

namespace WorkCosts.Data.Migrations
{
    [DbContext(typeof(WorkCostsDbContext))]
    [Migration("20260817131100_AddProductPricePoint")]
    partial class AddProductPricePoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");
#pragma warning restore 612, 618
        }
    }
}
