// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WorkCosts.Data;

#nullable disable

namespace WorkCosts.Data.Migrations
{
    [DbContext(typeof(WorkCostsDbContext))]
    [Migration("20260821120000_AddProductExtraYaml")]
    partial class AddProductExtraYaml
    {
    }
}
