// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WorkCosts.Data;

#nullable disable

namespace WorkCosts.Data.Migrations
{
    [DbContext(typeof(WorkCostsDbContext))]
    [Migration("20260819000100_AddWebCacheLookup")]
    partial class AddWebCacheLookup
    {
    }
}
