// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkCosts.Data;

#nullable disable

namespace WorkCosts.Data.Migrations
{
    [DbContext(typeof(WorkCostsDbContext))]
    [Migration("20260921233755_AddWorkJobDefinition")]
    partial class AddWorkJobDefinition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("WorkCosts.Models.CachedWebImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Domain");

                    b.HasIndex("PageUrl", "ImageUrl")
                        .IsUnique();

                    b.ToTable("CachedWebImages");
                });

            modelBuilder.Entity("WorkCosts.Models.CachedWebPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Domain");

                    b.HasIndex("PageUrl")
                        .IsUnique();

                    b.ToTable("CachedWebPages");
                });

            modelBuilder.Entity("WorkCosts.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CarDetailsId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageRelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleOrderJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vrm")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("VrmKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarDetailsId");

                    b.HasIndex("VrmKey")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("WorkCosts.Models.CarDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey")
                        .IsUnique();

                    b.ToTable("CarDetails", (string)null);
                });

            modelBuilder.Entity("WorkCosts.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WorkCosts.Models.GarageJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CarDetailsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconRelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("IntervalAnchorDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RepeatCombine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarDetailsId");

                    b.HasIndex("CarId");

                    b.ToTable("GarageJobs");
                });

            modelBuilder.Entity("WorkCosts.Models.GarageJobReferencedJob", b =>
                {
                    b.Property<Guid>("GarageJobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("GarageJobId", "JobId");

                    b.HasIndex("JobId");

                    b.ToTable("GarageJobReferencedJobs");
                });

            modelBuilder.Entity("WorkCosts.Models.GarageJobRepeatCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GarageJobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GarageJobId");

                    b.ToTable("GarageJobRepeatConditions");
                });

            modelBuilder.Entity("WorkCosts.Models.GarageJobRequiredProduct", b =>
                {
                    b.Property<Guid>("GarageJobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<short>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("GarageJobId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("GarageJobRequiredProducts");
                });

            modelBuilder.Entity("WorkCosts.Models.ItemOfWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CarDetailsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GarageJobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OdometerMiles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarDetailsId");

                    b.HasIndex("CarId");

                    b.HasIndex("GarageJobId", "OccurredAt");

                    b.ToTable("ItemsOfWork", (string)null);
                });

            modelBuilder.Entity("WorkCosts.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GaragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotesMarkdown")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("WorkCosts.Models.JobCarDetails", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarDetailsId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobId", "CarDetailsId");

                    b.HasIndex("CarDetailsId");

                    b.ToTable("JobCarDetails", (string)null);
                });

            modelBuilder.Entity("WorkCosts.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraYaml")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageBlob")
                        .HasColumnType("BLOB");

                    b.Property<string>("ImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAllJobs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OemEquivalent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PricePoint")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Variation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WorkCosts.Models.ProductEquivalent", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquivalentProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId", "EquivalentProductId");

                    b.HasIndex("EquivalentProductId");

                    b.ToTable("ProductEquivalents", t =>
                        {
                            t.HasCheckConstraint("CK_ProductEquivalent_NotSelf", "ProductId <> EquivalentProductId");
                        });
                });

            modelBuilder.Entity("WorkCosts.Models.ProductJob", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId", "JobId");

                    b.HasIndex("JobId");

                    b.ToTable("ProductJobs");
                });

            modelBuilder.Entity("WorkCosts.Models.WorkJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefinition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("JobId");

                    b.ToTable("WorkJobs");
                });

            modelBuilder.Entity("WorkCosts.Models.WorkJobItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<short>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitCostSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkJobId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WorkJobId", "ProductId")
                        .IsUnique();

                    b.ToTable("WorkJobItems");
                });

            modelBuilder.Entity("WorkCosts.Models.Car", b =>
                {
                    b.HasOne("WorkCosts.Models.CarDetails", "CarDetails")
                        .WithMany()
                        .HasForeignKey("CarDetailsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CarDetails");
                });

            modelBuilder.Entity("WorkCosts.Models.GarageJob", b =>
                {
                    b.HasOne("WorkCosts.Models.CarDetails", "CarDetails")
                        .WithMany()
                        .HasForeignKey("CarDetailsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkCosts.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Car");

                    b.Navigation("CarDetails");
                });

            modelBuilder.Entity("WorkCosts.Models.GarageJobReferencedJob", b =>
                {
                    b.HasOne("WorkCosts.Models.GarageJob", "GarageJob")
                        .WithMany("ReferencedJobs")
                        .HasForeignKey("GarageJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkCosts.Models.Job", "Job")
                        .WithMany("GarageJobReferences")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GarageJob");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("WorkCosts.Models.GarageJobRepeatCondition", b =>
                {
                    b.HasOne("WorkCosts.Models.GarageJob", "GarageJob")
                        .WithMany("RepeatConditions")
                        .HasForeignKey("GarageJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GarageJob");
                });

            modelBuilder.Entity("WorkCosts.Models.GarageJobRequiredProduct", b =>
                {
                    b.HasOne("WorkCosts.Models.GarageJob", "GarageJob")
                        .WithMany("RequiredProducts")
                        .HasForeignKey("GarageJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkCosts.Models.Product", "Product")
                        .WithMany("GarageJobRequiredProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GarageJob");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WorkCosts.Models.ItemOfWork", b =>
                {
                    b.HasOne("WorkCosts.Models.CarDetails", "CarDetails")
                        .WithMany()
                        .HasForeignKey("CarDetailsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkCosts.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkCosts.Models.GarageJob", "GarageJob")
                        .WithMany("ItemsOfWork")
                        .HasForeignKey("GarageJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("CarDetails");

                    b.Navigation("GarageJob");
                });

            modelBuilder.Entity("WorkCosts.Models.JobCarDetails", b =>
                {
                    b.HasOne("WorkCosts.Models.CarDetails", "CarDetails")
                        .WithMany("JobLinks")
                        .HasForeignKey("CarDetailsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkCosts.Models.Job", "Job")
                        .WithMany("CarDetailsLinks")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarDetails");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("WorkCosts.Models.Product", b =>
                {
                    b.HasOne("WorkCosts.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WorkCosts.Models.ProductEquivalent", b =>
                {
                    b.HasOne("WorkCosts.Models.Product", "EquivalentProduct")
                        .WithMany("EquivalentOfLinks")
                        .HasForeignKey("EquivalentProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkCosts.Models.Product", "Product")
                        .WithMany("EquivalentLinks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquivalentProduct");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WorkCosts.Models.ProductJob", b =>
                {
                    b.HasOne("WorkCosts.Models.Job", "Job")
                        .WithMany("ProductJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkCosts.Models.Product", "Product")
                        .WithMany("ProductJobs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WorkCosts.Models.WorkJob", b =>
                {
                    b.HasOne("WorkCosts.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkCosts.Models.Job", "Job")
                        .WithMany("WorkJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("WorkCosts.Models.WorkJobItem", b =>
                {
                    b.HasOne("WorkCosts.Models.Product", "Product")
                        .WithMany("WorkJobItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkCosts.Models.WorkJob", "WorkJob")
                        .WithMany("Items")
                        .HasForeignKey("WorkJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("WorkJob");
                });

            modelBuilder.Entity("WorkCosts.Models.CarDetails", b =>
                {
                    b.Navigation("JobLinks");
                });

            modelBuilder.Entity("WorkCosts.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WorkCosts.Models.GarageJob", b =>
                {
                    b.Navigation("ItemsOfWork");

                    b.Navigation("ReferencedJobs");

                    b.Navigation("RepeatConditions");

                    b.Navigation("RequiredProducts");
                });

            modelBuilder.Entity("WorkCosts.Models.Job", b =>
                {
                    b.Navigation("CarDetailsLinks");

                    b.Navigation("GarageJobReferences");

                    b.Navigation("ProductJobs");

                    b.Navigation("WorkJobs");
                });

            modelBuilder.Entity("WorkCosts.Models.Product", b =>
                {
                    b.Navigation("EquivalentLinks");

                    b.Navigation("EquivalentOfLinks");

                    b.Navigation("GarageJobRequiredProducts");

                    b.Navigation("ProductJobs");

                    b.Navigation("WorkJobItems");
                });

            modelBuilder.Entity("WorkCosts.Models.WorkJob", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
